name: anacapa-crux
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::obitools=1.2.13
  - bioconda::ecopcr=0.5.0
  - bioconda::cutadapt=1.18
  - bioconda::blast=2.12.0
  - bioconda::bowtie2=2.3.5.1
  - bioconda::qiime=1.9.1